poller: 
  devices:
    - hostname: "127.0.0.1" #so changed to localhost for now
      community: "public"
      port: 1161
      version: 2 
  aggregator:
      address: "localhost"
      port: 5555

