poller:
  interval: 10  # poll every 10 seconds for testing
  timeout: 5    # SNMP timeout
  retries: 2   
  
  aggregator:
    address: "localhost"
    port: 5555
  devices:
    - hostname: "172.20.20.3"
      community: "public"
      version: 2
      port: 161
    - hostname: "172.20.20.9"
      community: "public" 
      version: 2
      port: 161
    - hostname: "172.20.20.17"
      community: "public"
      version: 2
      port: 161
    - hostname: "172.20.20.21"
      community: "public"
      version: 2
      port: 161
    - hostname: "172.20.20.5"
      community: "public"
      version: 2
      port: 161
    - hostname: "172.20.20.6"
      community: "public"
      version: 2
      port: 161
    - hostname: "172.20.20.20"
      community: "public"
      version: 2
      port: 161
    - hostname: "172.20.20.18"
      community: "public"
      version: 2
      port: 161
    - hostname: "172.20.20.11"
      community: "public"
      version: 2
      port: 161
    - hostname: "172.20.20.19"
      community: "public"
      version: 2
      port: 161

aggregator:
  # db_config
  database:
    path: "data/switchmap_test.db"
  
  # ZeroMQ configuration for receiving data from pollers
  zeromq:
    address: "*"
    port: 5555
  
  # Web server configuration (baaad me)
  web:
    host: "localhost"
    port: 8080

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 